name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA44DRHDY63NBDTF4G

          aws-secret-access-key: 8Z/R2twYIz571JUo7yGLXbRdEVnWkHYgbcnMJaoT

          aws-region: us-east-1  # Change to your region
      
      - name: Sync files to S3
        run: |
          aws s3 sync . s3://harsh-portfolio-website-885000707645 \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --cache-control "max-age=31536000,public" \
            --exclude "*.html" \
            --exclude "*.json"
          
          # HTML files with shorter cache
          aws s3 sync . s3://harsh-portfolio-website-885000707645 \
            --exclude "*" \
            --include "*.html" \
            --include "*.json" \
            --cache-control "max-age=300,public" \
            --content-type "text/html; charset=utf-8"
      
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2CNPCSWQW530U \
            --paths "/*"
      
      - name: Deployment Success
        run: echo "ðŸš€ Deployment completed successfully!"
